# Generated by Django 5.0.7 on 2024-08-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usergames', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergames',
            name='games',
            field=models.CharField(max_length=255),
        ),
    ]
