# Generated by Django 5.0.7 on 2024-08-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('regist', '0003_usergames'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usergames',
        ),
    ]
